spring:
  datasource:
    url: jdbc:mysql://47.112.105.123:3306/SpringBootCRUD?useUnicode=true&characterEncoding=utf8&useSSL=false
    #    ?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CST
    username: root
    password: 74110asd123.
    driver-class-name: com.mysql.cj.jdbc.Driver
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true



server:
  port: 9999
